image: node

stages:
  - test
  - publish

test:
  stage: test
  tags:
    - shared
  script:
    - npm ci && npm i -s --no-save graphql@^14.0.0 && npm t
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  only:
    - master
    - branches
  except:
    - tags

publish:
  stage: publish
  tags:
    - shared
  script:
    - npm publish
  only:
    - tags
  except:
    - /^(?!master).+@/
